/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/decide`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/common/IconButton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/common/Backbutton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/common/NotificationButton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ProjectFinished`; params?: Router.UnknownInputParams; } | { pathname: `/../components/RateService`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ConcludedContractChecker`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/contratations/accep-contract`; params?: Router.UnknownInputParams; } | { pathname: `/contratations/cancel-contract`; params?: Router.UnknownInputParams; } | { pathname: `/contratations/contract`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/decide`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/common/IconButton`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/common/Backbutton`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/common/NotificationButton`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ProjectFinished`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/RateService`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ConcludedContractChecker`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/contratations/accep-contract`; params?: Router.UnknownOutputParams; } | { pathname: `/contratations/cancel-contract`; params?: Router.UnknownOutputParams; } | { pathname: `/contratations/contract`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/decide${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/../components/common/IconButton${`?${string}` | `#${string}` | ''}` | `/../components/common/Backbutton${`?${string}` | `#${string}` | ''}` | `/../components/common/NotificationButton${`?${string}` | `#${string}` | ''}` | `/../components/ProjectFinished${`?${string}` | `#${string}` | ''}` | `/../components/RateService${`?${string}` | `#${string}` | ''}` | `/../components/ConcludedContractChecker${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/contratations/accep-contract${`?${string}` | `#${string}` | ''}` | `/contratations/cancel-contract${`?${string}` | `#${string}` | ''}` | `/contratations/contract${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/decide`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/common/IconButton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/common/Backbutton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/common/NotificationButton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ProjectFinished`; params?: Router.UnknownInputParams; } | { pathname: `/../components/RateService`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ConcludedContractChecker`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/contratations/accep-contract`; params?: Router.UnknownInputParams; } | { pathname: `/contratations/cancel-contract`; params?: Router.UnknownInputParams; } | { pathname: `/contratations/contract`; params?: Router.UnknownInputParams; };
    }
  }
}
