/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/decide`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ContractServiceBottomSheet`; params?: Router.UnknownInputParams; } | { pathname: `/contratations/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/provider-login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/provider-register`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/contratations/accep-contract`; params?: Router.UnknownInputParams; } | { pathname: `/contratations/cancel-contract`; params?: Router.UnknownInputParams; } | { pathname: `/professional/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/professional/add-service/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/professional/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/professional/edit-service/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/decide`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ContractServiceBottomSheet`; params?: Router.UnknownOutputParams; } | { pathname: `/contratations/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/provider-login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/provider-register`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/contratations/accep-contract`; params?: Router.UnknownOutputParams; } | { pathname: `/contratations/cancel-contract`; params?: Router.UnknownOutputParams; } | { pathname: `/professional/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/professional/add-service/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/professional/edit/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/professional/edit-service/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/decide${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/../components/ContractServiceBottomSheet${`?${string}` | `#${string}` | ''}` | `/contratations/[id]${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/provider-login${`?${string}` | `#${string}` | ''}` | `/auth/provider-register${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/contratations/accep-contract${`?${string}` | `#${string}` | ''}` | `/contratations/cancel-contract${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/decide`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ContractServiceBottomSheet`; params?: Router.UnknownInputParams; } | { pathname: `/contratations/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/provider-login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/provider-register`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/contratations/accep-contract`; params?: Router.UnknownInputParams; } | { pathname: `/contratations/cancel-contract`; params?: Router.UnknownInputParams; } | `/professional/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/professional/add-service/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/professional/edit/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/professional/edit-service/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/professional/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/professional/add-service/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/professional/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/professional/edit-service/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
